create table TAMANDARE.XMLDOCS (
DOC_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY, 
DOC_DATA XML, 
DOC_URL_HASH VARCHAR(255),
DOC_TAGS_HASH VARCHAR(255),
DOC_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP);

create table TAMANDARE.PRESESSIONS (
PRESESSIONS_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
PRESESSIONS_SOURCE_ENTITY VARCHAR(255), 
PRESESSIONS_TARGET_ENTITY VARCHAR(255), 
PRESESSIONS_DOC_DATA XML, 
PRESESSIONS_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP);

create table TAMANDARE.HISTORYCONN (
HISTORYCONN_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL UNIQUE,
HISTORYCONN_ADDR VARCHAR(255),
HISTORYCONN_ENTITY VARCHAR(255),
HISTORYCONN_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
PRIMARY KEY (HISTORYCONN_ADDR, HISTORYCONN_ENTITY));



CREATE TABLE TAMANDARE.JOBS (
JOBS_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
JOBS_THREAD VARCHAR(150) NOT NULL,
JOBS_INTERVAL INT NOT NULL,
JOBS_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP);
