#ALTER TABLE TAMANDARE.XMLDOCS 
#ADD COLUMN DOC_URL_HASH VARCHAR(255)

ALTER TABLE TAMANDARE.XMLDOCS 
ADD COLUMN DOC_TAGS_HASH VARCHAR(255);

drop table TAMANDARE.XMLDOCS;

create table TAMANDARE.XMLDOCS (
DOC_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY, 
DOC_DATA XML, 
DOC_URL_HASH VARCHAR(255),
DOC_TAGS_HASH VARCHAR(255),
DOC_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP);


select DOC_URL_HASH ,
DOC_TAGS_HASH from TAMANDARE.XMLDOCS;