#ALTER TABLE TAMANDARE.XMLDOCS 
#ADD COLUMN DOC_URL_HASH VARCHAR(255)

#ALTER TABLE TAMANDARE.XMLDOCS 
#ADD COLUMN DOC_TAGS_HASH VARCHAR(255);

#drop table TAMANDARE.XMLDOCS;




select DOC_URL_HASH ,
DOC_TAGS_HASH from TAMANDARE.XMLDOCS;